/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of QConf.xs. Do not edit this file, edit QConf.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "QConf.xs"
#ifdef __cpluscplus
extern "C"{
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cpluscplus
}
#endif
#include "ppport.h"
#include "qconf.h"
#include <string.h>


SV* get_conf(const char *path,SV *ret,const char *idc, const char *async)
{
	char *value = new char[1024*1024];	  
	memset(value,0,1024*1024);	  
	char *idc_ = NULL;
	if (strlen(idc) != 0)
		idc_ = (char*)idc;
    int err = 0;
    if(strcasecmp(async,"true") != 0)
    	err = qconf_get_conf(path, value, 1024*1024, idc_);
    else
    	err = qconf_aget_conf(path, value, 1024*1024, idc_);
    SV* errCode = newSViv(err);
    if (err != QCONF_OK)
    	goto final;
    sv_setpvn(ret,value,strlen(value));      
final:      
    delete [] value;
    return errCode;
}

SV* get_batch_conf(const char *path,HV *ret,const char *idc, const char *async)
{
	qconf_batch_nodes nodes;	
	int err = init_qconf_batch_nodes(&nodes);
	if (QCONF_OK != err)
		return newSViv(err);
	char *idc_ = NULL;
	if (strlen(idc) != 0)
		idc_ = (char*)idc;
	if(strcasecmp(async,"true") != 0)
		err = qconf_get_batch_conf(path,&nodes,idc_);
	else
		err = qconf_aget_batch_conf(path,&nodes,idc_);
	if (QCONF_OK != err){
		destroy_qconf_batch_nodes(&nodes);
		return newSViv(err);
	}
	for(int i=0;i<nodes.count;++i)
	{
		hv_store(ret,nodes.nodes[i].key,strlen(nodes.nodes[i].key),newSVpvn(nodes.nodes[i].value,strlen(nodes.nodes[i].value)),0);
	}	
	destroy_qconf_batch_nodes(&nodes);
	return newSViv(err);
}

SV* get_batch_keys(const char *path, AV *ret,const char *idc, const char *async)
{
	string_vector_t nodes;
	int err = init_string_vector(&nodes);
	if(QCONF_OK != err)
		return newSViv(err);
	char *idc_ = NULL;
	if (strlen(idc) != 0)
		idc_ = (char*)idc;
	if(strcasecmp(async,"true") != 0)
		err = qconf_get_batch_keys(path,&nodes,idc_);
	else
		err = qconf_aget_batch_keys(path,&nodes,idc_);
	if(QCONF_OK != err)
	{
		destroy_string_vector(&nodes);
		return newSViv(err);
	}
	for(int i = 0;i < nodes.count; ++i)
	{
		av_push(ret,newSVpvn(nodes.data[i],strlen(nodes.data[i])));
	}
	destroy_string_vector(&nodes);
	return newSViv(err);	
}

SV* get_batch_keys_native(const char *path, AV *ret,const char *idc, const char *async)
{
	string_vector_t nodes;
	int err = init_string_vector(&nodes);
	if(QCONF_OK != err)
		return newSViv(err);
	char *idc_ = NULL;
	if(strcasecmp(async,"true") != 0)
		idc_ = (char*)idc;
	if(!async)
		err = qconf_get_batch_keys_native(path,&nodes,idc_);
	else
		err = qconf_aget_batch_keys_native(path,&nodes,idc_);
	if(QCONF_OK != err)
	{
		destroy_string_vector(&nodes);
		return newSViv(err);
	}
	for(int i = 0;i < nodes.count; ++i)
	{
		av_push(ret,newSVpvn(nodes.data[i],strlen(nodes.data[i])));
	}
	destroy_string_vector(&nodes);
	return newSViv(err);	
}

SV* get_host(const char *path,SV *ret,const char *idc, const char *async)
{
	char *value = new char[1024*1024];	  
	memset(value,0,1024*1024);	  
	char *idc_ = NULL;
	if (strlen(idc) != 0)
		idc_ = (char*)idc;
    int err = 0;
    if(strcasecmp(async,"true") != 0)
    	err = qconf_get_host(path, value, 1024*1024, idc_);
    else
    	err = qconf_aget_host(path, value, 1024*1024, idc_);
    SV* errCode = newSViv(err);
    if (err != QCONF_OK)
    	goto final;
    sv_setpvn(ret,value,strlen(value));      
final:      
    delete [] value;
    return errCode;
}

SV* get_allhost(const char *path, AV *ret,const char *idc, const char *async)
{
	string_vector_t nodes;
	int err = init_string_vector(&nodes);
	if(QCONF_OK != err)
		return newSViv(err);
	char *idc_ = NULL;
	if (strlen(idc) != 0)
		idc_ = (char*)idc;
	if(strcasecmp(async,"true") != 0)
		err = qconf_get_allhost(path,&nodes,idc_);
	else
		err = qconf_aget_allhost(path,&nodes,idc_);
	if(QCONF_OK != err)
	{
		destroy_string_vector(&nodes);
		return newSViv(err);
	}
	for(int i = 0;i < nodes.count; ++i)
	{
		av_push(ret,newSVpvn(nodes.data[i],strlen(nodes.data[i])));
	}
	destroy_string_vector(&nodes);
	return newSViv(err);
}


#line 172 "QConf.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 316 "QConf.c"

XS_EUPXS(XS_QConf_qconf_init); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_qconf_init)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = qconf_init();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_qconf_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_qconf_destroy)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = qconf_destroy();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_get_conf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_get_conf)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "path, ret, idc, async");
    {
	SV *	RETVAL;
	const char *	path = (const char *)SvPV_nolen(ST(0))
;
	SV *	ret = ST(1)
;
	const char *	idc = (const char *)SvPV_nolen(ST(2))
;
	const char *	async = (const char *)SvPV_nolen(ST(3))
;

	RETVAL = get_conf(path, ret, idc, async);
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_get_batch_conf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_get_batch_conf)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "path, ret, idc, async");
    {
	SV *	RETVAL;
	const char *	path = (const char *)SvPV_nolen(ST(0))
;
	HV *	ret;
	const char *	idc = (const char *)SvPV_nolen(ST(2))
;
	const char *	async = (const char *)SvPV_nolen(ST(3))
;

	STMT_START {
		SV* const xsub_tmp_sv = ST(1);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVHV){
		    ret = (HV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not a HASH reference",
				"QConf::get_batch_conf",
				"ret");
		}
	} STMT_END
;

	RETVAL = get_batch_conf(path, ret, idc, async);
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_get_batch_keys); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_get_batch_keys)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "path, ret, idc, async");
    {
	SV *	RETVAL;
	const char *	path = (const char *)SvPV_nolen(ST(0))
;
	AV *	ret;
	const char *	idc = (const char *)SvPV_nolen(ST(2))
;
	const char *	async = (const char *)SvPV_nolen(ST(3))
;

	STMT_START {
		SV* const xsub_tmp_sv = ST(1);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    ret = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"QConf::get_batch_keys",
				"ret");
		}
	} STMT_END
;

	RETVAL = get_batch_keys(path, ret, idc, async);
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_get_batch_keys_native); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_get_batch_keys_native)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "path, ret, idc, async");
    {
	SV *	RETVAL;
	const char *	path = (const char *)SvPV_nolen(ST(0))
;
	AV *	ret;
	const char *	idc = (const char *)SvPV_nolen(ST(2))
;
	const char *	async = (const char *)SvPV_nolen(ST(3))
;

	STMT_START {
		SV* const xsub_tmp_sv = ST(1);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    ret = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"QConf::get_batch_keys_native",
				"ret");
		}
	} STMT_END
;

	RETVAL = get_batch_keys_native(path, ret, idc, async);
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_get_host); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_get_host)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "path, ret, idc, async");
    {
	SV *	RETVAL;
	const char *	path = (const char *)SvPV_nolen(ST(0))
;
	SV *	ret = ST(1)
;
	const char *	idc = (const char *)SvPV_nolen(ST(2))
;
	const char *	async = (const char *)SvPV_nolen(ST(3))
;

	RETVAL = get_host(path, ret, idc, async);
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_QConf_get_allhost); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_QConf_get_allhost)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "path, ret, idc, async");
    {
	SV *	RETVAL;
	const char *	path = (const char *)SvPV_nolen(ST(0))
;
	AV *	ret;
	const char *	idc = (const char *)SvPV_nolen(ST(2))
;
	const char *	async = (const char *)SvPV_nolen(ST(3))
;

	STMT_START {
		SV* const xsub_tmp_sv = ST(1);
		SvGETMAGIC(xsub_tmp_sv);
		if (SvROK(xsub_tmp_sv) && SvTYPE(SvRV(xsub_tmp_sv)) == SVt_PVAV){
		    ret = (AV*)SvRV(xsub_tmp_sv);
		}
		else{
		    Perl_croak_nocontext("%s: %s is not an ARRAY reference",
				"QConf::get_allhost",
				"ret");
		}
	} STMT_END
;

	RETVAL = get_allhost(path, ret, idc, async);
	RETVAL = sv_2mortal(RETVAL);
	ST(0) = RETVAL;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_QConf); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_QConf)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("QConf::qconf_init", XS_QConf_qconf_init);
        newXS_deffile("QConf::qconf_destroy", XS_QConf_qconf_destroy);
        newXS_deffile("QConf::get_conf", XS_QConf_get_conf);
        newXS_deffile("QConf::get_batch_conf", XS_QConf_get_batch_conf);
        newXS_deffile("QConf::get_batch_keys", XS_QConf_get_batch_keys);
        newXS_deffile("QConf::get_batch_keys_native", XS_QConf_get_batch_keys_native);
        newXS_deffile("QConf::get_host", XS_QConf_get_host);
        newXS_deffile("QConf::get_allhost", XS_QConf_get_allhost);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

