/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qihoo_qconf_Qconf */

#ifndef _Included_net_qihoo_qconf_Qconf
#define _Included_net_qihoo_qconf_Qconf
#ifdef __cplusplus
extern "C" {
#endif

    
#define QCONF_JAVA_CONF_BUF_MAX_LEN (256*1024)
#define QCONF_ERR_JAVA_CONVERT_LIST 91
#define QCONF_ERR_JAVA_CONVERT_MAP 92


/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qihoo_qconf_Qconf_init
  (JNIEnv *, jclass);

/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qihoo_qconf_Qconf_destroy
  (JNIEnv *, jclass);

/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    getConf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_qihoo_qconf_Qconf_getConf
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    getHost
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_qihoo_qconf_Qconf_getHost
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    getAllHost
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_qihoo_qconf_Qconf_getAllHost
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    getBatchConf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_net_qihoo_qconf_Qconf_getBatchConf
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     net_qihoo_qconf_Qconf
 * Method:    getBatchKeys
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_net_qihoo_qconf_Qconf_getBatchKeys
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
